language: go
services: docker
env:
  global:
  - DOCKER_USER=callforamerica
  # DOCKER_PASS
  - secure: "htVwUkp2O1Z0gWAi2YQ/ubpuPKUlswXwAMzxdKzTNvN8mfDW8QpJz8SIQkj/9Asxl3HKUThGolSEgVNX9CnMIAxM1ZkOJJ8s1lAR+aERlgIpj/IPZfqU0iccX5ZceCglgGMkPaF901e0fr/XysgAKJuy9pHrvxq9Ii611ghKdswqpZK9LPcYwkxwV8YlYf0IFBuZTIXzYVGIN4bsHAbqC9Xo7DzXN65TgVunjOKmLieRMXZ7HP2gEJ095zhcvJjzOZPEV9La6htVeCeq0KXj7iYMS68aCaVh7O0a0E5SlTykD0WVRPGoKKtM/yv1JQqo3DEG3MEivBgSqpURnZN+iFIrxKuCDdk193jYrb8RGYMYqrWfE9z8XJWWcqr0A07zIglM18zogufgtA5Na72/4qOXDx1oS9o6lRp0nORVcvsNKhLjyjHTi2QtPAcPa5KJVLwmXCMc2ZfQxv3Xzc7YRCbGEMNM//FHsoRFYDiCxHdF+Km8e4FgEBz2c8bclGe3w2vglnRCbm2O/uSvU2CS8WJaA3GgtUitDxuT/oPofBC7cer0/Ohv01VG9IySZahefNmH4E3Bb5LjpLoUgLqWdZJk3tReYtEdBv5UbHpchD+FTsZ1RIyw94Z9QXdRMzpXzO2Mu2k9xN2rO5zfdBjPQLt6Wv+0ilvDF19NO5uCPgo="
  # GITHUB_TOKEN
  - secure: "tUINrQArSdDK3QeLDe6URYFTuWkMa4tq2OmE3C6NYRKwAp8ZOtw9Veh6uFdSNV+yqyELhFlHpNjEQ9Hd2G5z9r+yd4gJiSRrM/1Q0fkogDJWmuer61R6fZ1/9WrcngpkYQ4nIXUKS+oztdAL4+Ksuq7kEqlp/GUfWMJutn8BlpQxJ773Ocsdb8NjgXmf5RoUHlYIIcVBOo0JLERnCRqrMmmoemlSvNlte7Wn+3gB/Ew0bxanTMt4e/e8JmCANKrr4jhB3+KJzucxLdd8/Mmo7YovJgacZjjdXJcNETSLgi4lkeHBD9xlkOVc/IXlQQQvf+HOX/kkGFLE1lNpmdveeRj9yxF5tsKwCAfU/szje+MtCb0QNgDilbRKp0TxiVhgHxCfi9w7qa+Bk7u9jySIRx0VodVO7nN/beDe5sgx0k26n9Xo4RpHNoMtFDkxYYH6I7vEBghF+3cx1T5IDpS/FQJ4NAw6pOzJnc91mJp/747ND/dFIHBIfpYJnFw97SaJhoCtDgmLPLFP+lw9M/7iPC+ef17ojAojgGqA4zYY/n0HodndPK4XAmo/l/zjX7uX98LWu34AEDYIOqxevpV96pu/vhNOYg2DX2s4PkWHYSw8fYagToGURKECZDA9pMaH2bLVNmPXocaPZ6Q52/qPoa84ig+vCbwGeN9/WBOcb2U="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "hyOuSVXvzb9mVT8crXZG2RMuAKWpP9/iIOz6LMaSHMaHNmS2+AtRQinnxJa+RzGYLLFSZGZtnFEIHfGUSTfDyzYuORRvcubz5sfUGpau/1hcqU+ANLV96W/dBfMzXO9m88YxAMefrWu6SBIT+YeE+Qq9QVCiEF+FIrulL1SYfYzpe+a1C3/wtKSBe8qyv6Fn1Ij3nkfyE4UsMlpVzFIjNq7HkcYFnwmuL97DGPET3JunJCxv9ZgCudbVC30G4kt0oUaml6reqfFVkLkW6FegdojzXAdL+8OKytL8Hsc2nVOHGJiED40K5gqSOERMtCPNwevHgBZsDN2GBuqxbErtS8ykJ4IA0xr0u/50j94sY+2xLqFbnMfpV/9siojbyZPXC5rSq+NsTXDcrUC+FJ3u+rFTCSY78/GJ3eUrGqs79DBTukZsvTch9Q1PE0XsZUFEKBe10x5YKUN1W+LJHD0e4FcSOQVA4USzlC8xZnreiMlpkxAnVyq5n3w5WbhPcuiqRaul9N8Sdl/0Z2g62ilhElactcF43KkYb67vvUT9dYSXqdz0+Sr9NyXMypaoFgrLeziXSRpICa75KZ2h3/qb4F5H6jpcR+cAMZYTn17ImZj0tm5SsnEFdWvTa65bMD/SE1wW9ni9WUJ2Lte1fxMI7Y8b87ecZz6IdbcLpOLSvFg="
    on_success: always
    on_failure: always
branches:
  only:
  - master

before_install:
- go get github.com/aktau/github-release
- source scripts/ci/environment.sh

install: travis_wait 25 make build

script:
- make export

after_success:
- ci-tag-build
- hub-push
- bump-version
- make-release
- upload-release
